services:
  ollama:
    image: ollama/ollama:0.4.3
    container_name: ollama
    runtime: nvidia
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: no

  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    runtime: nvidia
    ports:
      - "3000:8080"
    volumes:
      - ./open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: no

